import Nav from '@/components/NavComponent/Nav'
import './globals.css'
import 'material-symbols';
import Script from 'next/script';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body>
                
{/* <!-- Google tag (gtag.js) --> */}
<Script strategy='afterInteractive' src="https://www.googletagmanager.com/gtag/js?id=G-07J2SQ3D3C"></Script>
<Script strategy='afterInteractive' dangerouslySetInnerHTML={{__html:`
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-07J2SQ3D3C');

`}} id="gtag"></Script>

      <Nav />
        {children}


        </body>
    </html>
  )
}
